// REDUX ACTION TYPES

export const AUTHENTICATOR_LOADING = 'AUTHENTICATOR_LOADING'
export const AUTHENTICATOR_SUCCESS = 'AUTHENTICATOR_SUCCESS'
export const AUTHENTICATOR_ERROR = 'AUTHENTICATOR_ERROR'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'


